import Head from 'next/head'
import type { GetStaticProps, NextPage } from 'next'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Character, GetCharacterResults } from '@/types'

const inter = Inter({ subsets: ['latin'] })

const Home:NextPage<{characters: Character}> = ({characters}) => {
  console.log("results ",characters)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       {characters.map((character,i) => {
        return (
          <div key={i}>
            {character.name}
            {/* <Image
            src={character.image}
            alt={character.name}
            width='200'
            height='200'
            /> */}
          </div>
        )
       })}
      </main>
    </>
  )
}

export default Home;

export const getStaticProps:GetStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character');
  const { results }: GetCharacterResults = await res.json();
  //console.log("res ",results)

  return {
    props: {
      characters : results
    }
  }
} 